name: lembrar_mais
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.3.0
  circular_menu: ^2.0.1
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/registro_responsavel.png
    - assets/images/registro_idoso.png
