// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc5LG1tjW1WdhAhzaS9swJA-PTVQljrAM',
    appId: '1:875106073339:web:ec1c2cab012b7f5c018e5e',
    messagingSenderId: '875106073339',
    projectId: 'lembrar-mais-9ed96',
    authDomain: 'lembrar-mais-9ed96.firebaseapp.com',
    storageBucket: 'lembrar-mais-9ed96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdDknT6iIOB9bF3DTn2oEe2yn2hNBBbA',
    appId: '1:875106073339:android:c1b708327533a41d018e5e',
    messagingSenderId: '875106073339',
    projectId: 'lembrar-mais-9ed96',
    storageBucket: 'lembrar-mais-9ed96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvi1XUMuMg6I0bPYJivxcqeWoOpbjC_dY',
    appId: '1:875106073339:ios:aca5b793a30f144e018e5e',
    messagingSenderId: '875106073339',
    projectId: 'lembrar-mais-9ed96',
    storageBucket: 'lembrar-mais-9ed96.firebasestorage.app',
    iosBundleId: 'com.example.lembrarMais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvi1XUMuMg6I0bPYJivxcqeWoOpbjC_dY',
    appId: '1:875106073339:ios:aca5b793a30f144e018e5e',
    messagingSenderId: '875106073339',
    projectId: 'lembrar-mais-9ed96',
    storageBucket: 'lembrar-mais-9ed96.firebasestorage.app',
    iosBundleId: 'com.example.lembrarMais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc5LG1tjW1WdhAhzaS9swJA-PTVQljrAM',
    appId: '1:875106073339:web:513d4802c98044ac018e5e',
    messagingSenderId: '875106073339',
    projectId: 'lembrar-mais-9ed96',
    authDomain: 'lembrar-mais-9ed96.firebaseapp.com',
    storageBucket: 'lembrar-mais-9ed96.firebasestorage.app',
  );
}
